server:
  port: ${PORT:8011} 

spring:    
  application:
    name: products-microservice 
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:inditexdb
    driverClassName: org.h2.Driver
    username: sa
    password: 1234
    data: classpath:/SQL/price_schema.sql, classpath:/SQL/price_data.sql

eureka:         
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 2
#    statusPageUrlPath: ${server.servlet.context-path}/info
#    healthCheckUrlPath: ${server.servlet.context-path}/health
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka-config/eureka
    healthcheck:
      enabled: true
    lease:
      duration: 5
    fetch-registry: true
     
management:
  endpoints:
    web:
      exposure:
        include: "*"
  security:
    enabled: false  

 
logging:
  level:
    com.company.ms_products: DEBUG
