server:
  port: ${PORT:8761}
  servlet:
   context-path: /eureka-config
 
eureka:
  client:
    registryFetchIntervalSeconds: 5
#    registerWithEureka: false
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka-config
  instance:
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: ${DISCOVERY_URL:http://localhost:8761}/info
    healthCheckUrlPath: ${DISCOVERY_URL:http://localhost:8761}/health

 
management:
  endpoints:
    web:
      exposure:
        include: "*"
  security:
    enabled: false

#spring:
#  boot:
#    admin:
#      context-path: /admin  #A different context path for admin server has been provided not conflicting with eureka
